### ISSUE TITLE
Question: how to use Read Scale Script

### ISSUE THREAD

**Issue by jonbur** [frangoteam/FUXA#1533]
Hi, I hope you can help. I am having trouble with Read Scale Script and can't find any documentation.

I have several tags coming from mqtt that hves the value either 'on' or 'off', as below:

<img width="1296" alt="Screenshot 2024-12-09 at 15 23 54" src="https://github.com/user-attachments/assets/8a6fbd8e-fb31-43c3-9644-aae66afb7220">

I would like to use this to drive Actions on a shape. I understand that Actions can only be driven by numerical values and therefore I am looking to convert the text values to equivalent numerical/binary values (1/0). I have created the script below and assigned it as the Read Scale Script.

<img width="395" alt="Screenshot 2024-12-09 at 15 23 25" src="https://github.com/user-attachments/assets/cbca5009-9805-4f58-9959-0142959537fa">

<img width="1082" alt="Screenshot 2024-12-09 at 15 24 32" src="https://github.com/user-attachments/assets/0f153d89-f2d9-488b-8529-62120a7d8b76">

However, this does not appear to work. There is no error in the logs. Even if I change the script to simply just 'return 1' in all cases I don't see a change to the value of the tag. 

Am I missing something?

Thank you very much.

**Comment by MatthewReed303** [comment]
@jonbur at the bottom of the page https://github.com/frangoteam/FUXA/wiki/HowTo-Devices-and-Tags

**Comment by jonbur** [comment]
Hi,

Thanks for this. I have seen this and believe I have followed the design pattern shown, but it does not look like the script is being applied / changing the output. 

Just to make sure I have this correct conceptually, the 'value' that is passed into the read script is the tag value that is read from the integration connector (in this case mqtt) and then the script manipulates it and whatever is returned should then be what we see when that tag is used elsewhere?

Thank you

**Comment by henjoe** [comment]
Your script is actually correct. I dont know why it is not working.

**Comment by unocelli** [comment]
Hi, try to debug with a console.log(value);

**Comment by jonbur** [comment]
Thanks. If I run the script in the script editor with console logging, I get the below:

<img width="1356" alt="Screenshot 2024-12-15 at 11 56 57" src="https://github.com/user-attachments/assets/5d69f38e-418e-4177-985c-cc2ed962244a" />

This seems fine (although I note I don't get return '0' when I call with 'off'...

Is there a logger object I can use to log to fuxa.log from within the script so I can see whether this script is actually getting caleld by the 'read scale script' defined on the tag?

Thanks

**Comment by henjoe** [comment]
Hi @unocelli  the  issue might be related to #1435

**Comment by unocelli** [comment]
Try to return a string '0'

**Comment by jonbur** [comment]
Hi,

Sorry, this still does not appear to work.

With the script below:

<img width="1356" alt="Screenshot 2024-12-15 at 11 56 57" src="https://github.com/user-attachments/assets/754d112e-d499-4d46-9946-2ba7e6d9feed" />

Applied as the 'Read Scale Script' on a tag as per the below:

<img width="1293" alt="Screenshot 2024-12-18 at 22 40 28" src="https://github.com/user-attachments/assets/9df89fe4-c4f5-4999-b77b-5b41dd1ba0ac" />

The value does not change (see circled in red). It also does not change in the action on the object in the editor - it is still 'on' or 'off'.

Even is I just do this:

<img width="606" alt="Screenshot 2024-12-18 at 22 39 32" src="https://github.com/user-attachments/assets/d525836b-652c-442d-bbe0-eba3bf9cd0d2" />

the value does not change.
It is like the script is not being called at all...

Thanks

**Comment by jonbur** [comment]
Thanks very much, I’ll test the latest version over the weekend :-)

**Comment by 851666395** [comment]
> Thanks very much, I’ll test the latest version over the weekend :-)

I have also encountered similar problems in webAPI。

![QQ截图20241220230800](https://github.com/user-attachments/assets/468977ba-80b7-40fc-abbb-88c1e529aaf7)

![QQ截图20241220230924](https://github.com/user-attachments/assets/ac43da46-fa86-4b6e-8a7d-e57da0f85960)

**Comment by 851666395** [comment]
> Hi, sorry, you are right! in mqtt is missing a reference to process the script

HI,I have also encountered similar problems in webAPI。

**Comment by unocelli** [comment]
@851666395 Hi, Yes should be fixed in mqtt, ethernetip and httprequest (WebApi)

**Comment by 851666395** [comment]
> @851666395 Hi, Yes should be fixed in mqtt, ethernetip and httprequest (WebApi)

thank you，I'll try again when it's fixed。

**Comment by jonbur** [comment]
Thanks, I can confirm the latest release is working for me.
Thank you.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by H-hejin** [comment]
> I’m going to close this as resolved. let me know if you have any issues.

Why do the Pro version I downloaded still have the issues mentioned above, which makes me very distressed? 1.2.0

**Comment by unocelli** [comment]
You’re using an old version, please download the latest one (currently 1.2.5), where those issues should be fixed.
