### ISSUE TITLE
Read Memory Data of PLC S7

### ISSUE THREAD

**Issue by kotori94** [frangoteam/FUXA#54]
Hi, I can read Data Block of PLC S7 (e.g: DB1.DBD0), but I cannot read Memory Data of PLC S7 (e.g: MD44). How can I read that? thanks

**Comment by unocelli** [comment]
Hi, the node-snap7 should support it but is missing in the wrapper that I have implemented.
I don't use read Memory. I can try to extend my wrapper...How can I simulate PLC Memory Data in my PC?

**Comment by kotori94** [comment]
Hi, node-snap 7 support S7Client.MBRead and MBWrite function, but your source code only implemented DBRead and write. About simulating, you can try s7 simulator software. Hope you can fix this soon.

**Comment by kotori94** [comment]
Or maybe you should try ReadMultiVars and WriteMultiVars function from node-snap7 instead of DBRead only

**Comment by unocelli** [comment]
Hi, I agree that it is better to use ReadMultiVars/WriteMultiVars for all other kinds of variables.
I will try to fix it. thanks

**Comment by kotori94** [comment]
Hi, how was it going? I tried to custom code but still cannot read it

**Comment by unocelli** [comment]
Hi, I'm working to fix it. I will use ReadMultiVars / WriteMultiVArs only
for Output, Input and Merkers, the DB have to be grouped and operated with
DBRead for performance aspects by DAQ.
To simulate the PLC Server I'm using the CSharp Project from
http://snap7.sourceforge.net/

Hi, how was it going? I tried to custom code but still cannot read it

**Comment by unocelli** [comment]
Hi, I fixed it. Thanks

**Comment by kotori94** [comment]
It worked. Thank you
